spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ivmsDB
      database: ivmsDB
      host: localhost
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

jwt :
  secret: your-jwt-secret
  expiration: 3600