spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ivmsDB
      database: ivmsDB
      host: localhost
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

security:
  jws:
    connection-timeout: 600
    read-timeout: 600
    url: "????"
    max-clock-skew-seconds: 3

jwt :
  secret: your-jwt-secret
  expiration: 3600