managment:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
        database: user-service-db
        host: localhost
        port: 27017
        username: root
        password: '{cipher}c3VwZXJzZXJ2aWNlLXNlY3JldA=='