spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-service-db
#      username: your_username
#      password: your_password
      authentication-database: admin
      auto-index-creation: true

ivms:
  app:
    jwtCookieName: ivms
    jwtSecret: "======================ivms=Spring==========================="
    jwtExpirationMs: 86400000