ivms:
  app:
    jwtCookieName: ivms
    jwtSecret: 12345678901234567890123456789012
    jwtExpirationMs: 86400000


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?readPreference=primary'
      database: ivms-user-service-db
      host: localhost
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

server:
  port: 8082