spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      username: <username>
      password: <password>
      authentication-database: admin

ivms:
  app:
    jwtCookieName: ivms
    jwtSecret: "======================ivms=Spring==========================="
    jwtExpirationMs: 86400000