spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service-db
      database: ivmsDB
      host: localhost
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

server:
  port: 8082