spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/?readPreference=primary'
      database: ivms-user-service-db
      host: localhost
  profiles:
    active: dev

logging:
  pattern.console: "%clr(%5p) %clr([traceid=%X{traceId:-} spanid=%X{spanId:-} parentspanid=%X{parentId:-}]){green} ${PID:-} --- [%-15.15thread] %-40.40logger{39} : %replace(%msg %rEx{10}){'[\r\n]+', '\u2028'}%nopex%n"
  level:
    ROOT: warn
    com.challenge.ivms: info

server:
  port: 8082


ivms:
  app:
    jwtCookieName: jwt-token
    jwtSecret: 1234567890
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 86400000
    jwtRefreshCookieName: jwt-refresh-token
