spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service-db
      authentication-database: admin
      auto-index-creation: true

ivms:
  app:
    jwt:
      clientId: glee-o-meter
      client-secret: secret
      accessTokenValidititySeconds: 120
      refreshTokenValiditySeconds: 1000
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem