spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service-db
      authentication-database: admin
      auto-index-creation: true

ivms:
  app:
    jwtCookieName: ivms
    jwtSecret: "ivms-secret-key"
    jwtExpirationMs: 86400000