spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service-db
      authentication-database: admin
      auto-index-creation: true

ivms:
  app:
    jwtSecret: "CXTEfksQdSDUo9beScR1On+ysewzcl+xafurP0bBAS3xv34twbOICesXTGDw6qvLzaPuS+2hJCKyoDQ6cWllvA=="
    jwtExpirationMs: 86400000 # JWT expiration time in milliseconds (24 hours)
    jwtCookieName: "ivms-jwt-cookie-name"
