managment:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
        database: user-service-db
        host: localhost
        port: 27017
        username: root
        password: '{cipher}c820ff447a0cf5ce7d612c0d38c2fb86da35464a5e9aa8804e579d29be4f4725'