spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/order-service-db
      database: ivmsDB
      host: localhost
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

server:
    port: 8083