
spring:
  application:
    name: ivms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BaharAdineh/InventoryManagementSystem-Configuration.git

server:
  ssl:
    key-store:  classpath:InventoryManagementSystem.p12
    key-alias: InventoryManagementSystem
    client-auth: need
