server.port: 8888
spring:
  application:
    name: ivms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BaharAdineh/InventoryManagementSystem-Configuration.git